# Generated by Django 3.2.6 on 2021-12-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20211221_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='tokenData',
            new_name='info',
        ),
    ]
