# Generated by Django 3.2.6 on 2021-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtoken',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='token_type',
        ),
        migrations.RemoveField(
            model_name='gmailtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='gmailtoken',
            name='tokenData',
            field=models.JSONField(null=True),
        ),
    ]
